### ISSUE TITLE
Compile errors on Vector Generation

### ISSUE THREAD

**Issue by dza6549** [kennux/VHair#1]
Hi @kennux 

I found this code via Unity List and would love to have a look.

Could you please advice what I might do to fix the error?

I've installed Unity.Math and Unity.Burst but get the following errors relating to vector generation:

Assets/Maths/Unity.Mathematics.CodeGen/VectorGenerator.cs(1969,23): error CS1502: The best overloaded method match for `Unity.Mathematics.Random.Random(uint)' has some invalid arguments

Assets/Maths/Unity.Mathematics.CodeGen/VectorGenerator.cs(1969,41): error CS1503: Argument `#1' cannot convert `int' expression to type `uint'

Assets/Maths/Unity.Mathematics.CodeGen/VectorGenerator.cs(2001,62): error CS1061: Type `Unity.Mathematics.Random' does not contain a definition for `Next' and no extension method `Next' of type `Unity.Mathematics.Random' could be found. Are you missing an assembly reference?

Thanks

Cheers!

**Comment by kennux** [comment]
This seems to be an issue in the Unity.Mathematics package. Make sure it's the newest.
What unity version are you on?
I'm developing this project currently on 2018.2.0f2, I'm not sure if it works with any other version.

Try to reinstall the Unity.Mathematics package or best clone the project fresh again and let unity reinstall all the packages on its own.
If that doesn't help check if the problem also happens on an empty unity project (create empty project, Window -> Package Manager -> All -> Mathematics -> Install (right pane, top right button)).

**Comment by dza6549** [comment]
Thanks @kennux 

Works a treat! and very impressive!

Sorry I forgot to give the (obviously required) details:
Unity 2018.2.16f1
Burst 0.2.4
Mathematics 0.0.12

Yes I did not know I could get Burst and Math via Package Manager, so I probably had old Clones.

Cheers!
