### ISSUE TITLE
VHAIR HDRP Tests

### ISSUE THREAD

**Issue by sasa42** [kennux/VHair#2]
Hi,

i did some rendering and llghting test who worked out great.

https://forum.unity.com/threads/will-dots-get-us-real-time-hair.784583/#post-5332704

Would be nice if you could join the thread on the Unity forum.

**Comment by sasa42** [comment]
Following some questions:

1) Is it possible to generate 16 or 12 vertices per strand to 
    smooth out the highlights for longer hair.

2) I have some issues with the render facing 
    implementation.
    The hair disapears on very camera closeups and 
    some large camera angles. I tried to correct your facing 
    but without success.

3) I use 3 times pony, cap and fringe meshes with and 
    slight  offset to generate the volume. 2 opaque layers 
    and one 
    transparent additive blended.
    I only would need the burst calculations for one pony, cap 
    and fringe set and tranfer the calculations to the offset
    ones. Is that possible?
4. The new mesh api in 2020 could further improve your 
    performance. Do you plan to integrate these?

 https://github.com/Unity-Technologies/MeshApiExamples-2020.1
in special
https://docs.google.com/document/d/1QC7NV7JQcvibeelORJvsaTReTyszllOlxdfEsaVL2oA/edit

**Comment by kennux** [comment]
Thanks for notifying me, questions were answered in the forum thread.
